version: '3'

volumes:
  database:
    driver: local

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.32
    container_name: bakery_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bakery
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      # DATABASE_URL: mysql://root@127.0.0.1:3306/bakery
    volumes:
      - database:/var/lib/mysql
